version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CACHE_TIME=${CACHE_TIME}
      - USE_CAPTION_FILTER=${USE_CAPTION_FILTER}
      - PICS=${PICS}
      - ADMINS=${ADMINS}
      - CHANNELS=${CHANNELS}
      - DATABASE_URI=${DATABASE_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - SUPPORT_CHAT=${SUPPORT_CHA}
      - P_TTI_SHOW_OFF=${P_TTI_SHOW_OFF}
      - IMDB=${IMDB}
      - SINGLE_BUTTON=${SINGLE_BUTTON}
      - CUSTOM_FILE_CAPTION=${CUSTOM_FILE_CAPTION}
      - BATCH_FILE_CAPTION=${BATCH_FILE_CAPTION}
